import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MagicProvider from '@/app/context/MagicProvider';
import { UserProvider } from '@/app/context/UserContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MagicProvider>
        <UserProvider>{children}</UserProvider>
      </MagicProvider>
      </body>
    </html>
  );
}
